[package]
name = "ling"
version = "0.1.0"
authors = ["chaosannals <chaosannals@outlook.com>"]
edition = "2018"

[dependencies]

[[bin]]
name = "ling"
path = "source/main.rs"

[[example]]
name = "ling-demo"
path = "source/demo.rs"